export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
  --highlight-line \
  --info=inline-right \
  --ansi \
  --layout=reverse \
  --border=none \
  --color=bg+:#003674 \
  --color=bg:#000000 \
  --color=border:#3986cc \
  --color=fg:#ededed \
  --color=gutter:#000000 \
  --color=header:#ff9300 \
  --color=hl+:#ededed \
  --color=hl:#ededed \
  --color=info:#454545 \
  --color=marker:#f12b82 \
  --color=pointer:#f12b82 \
  --color=prompt:#ededed \
  --color=query:#ededed:regular \
  --color=scrollbar:#3986cc \
  --color=separator:#ff9300 \
  --color=spinner:#f12b82 \
"
