# vim: ft=dosini
#
# aerc Vercel styleset
# set styleset-name=vercel-xxx.ini in 'aerc.conf' to load the style
#

*.default=true
*.normal=true

border.fg=#eaeaea
border.bg=#ffffff

title.fg=#ffffff
title.bg=#005ff2
title.bold=true

header.fg=#d8001b
#header.bg=#ffffff
header.bold=true

tab.fg=#eaeaea
tab.bg=#fafafa
tab.selected.fg=#ffffff
tab.selected.bg=#005ff2

statusline_default.fg=#171717
statusline_default.bg=#fafafa
statusline_error.fg=#fc0035
statusline_success.fg=#007f70

*error.bold=true
*error.fg=#fc0035
*warning.fg=#ffae00
*success.fg=#007f70

dirlist_*.bg=#ffffff
dirlist_*.fg=#171717
dirlist_*.selected.bg=#cae7ff
dirlist_*.selected.fg=#171717

msglist_*.bg=#ffffff
msglist_*.fg=#171717
msglist_*.selected.bg=#cae7ff
#msglist_*.selected.fg=#171717
msglist_unread.bold=true
msglist_unread.fg=#005ff2
msglist_marked.fg=#aa4d00
msglist_thread_folded.italic=true
msglist_thread_folded.underline=true
msglist_gutter.bg=#f2f2f2
msglist_pill.bg=#eaeaea
msglist_pill.reverse=false

part_*.fg=#171717
part_*.bg=#fafafa
part_*.selected.fg=#171717
part_*.selected.bg=#eaeaea

completion_default.bg=#fafafa
completion_default.fg=#171717
completion_default.selected.bg=#eaeaea
completion_default.selected.fg=#171717
completion_gutter.bg=#f2f2f2
completion_pill.bg=#eaeaea
completion_pill.reverse=false

spinner.bg=#ffffff
spinner.fg=#171717

selector_focused.bold=false
selector_focused.bg=#cae7ff
selector_focused.fg=#171717
selector_chooser.bold=false
selector_chooser.bg=#cae7ff
selector_chooser.fg=#171717
default.selected.bold=false
default.selected.fg=#171717
default.selected.bg=#cae7ff

[viewer]
url.underline=true
url.fg=#a8a8a8
header.fg=#7d00cc
signature.fg=#a000f8
diff_add.fg=#c9ead1
diff_del.fg=#febfcd
diff_meta.bold=true
diff_chunk.dim=true
quote_1.fg=#ffae00
quote_2.fg=#107d32
quote_3.fg=#00ac96
quote_3.dim=true
quote_4.fg=#005ff2
quote_4.dim=true
quote_x.fg=#4d4d4d
quote_x.dim=true

