# vim: ft=dosini
#
# aerc Vercel styleset
# set styleset-name=vercel-xxx.ini in 'aerc.conf' to load the style
#

*.default=true
*.normal=true

border.fg=#2e2e2e
border.bg=#000000

title.fg=#000000
title.bg=#47a8ff
title.bold=true

header.fg=#f13242
#header.bg=#000000
header.bold=true

tab.fg=#2e2e2e
tab.bg=#0a0a0a
tab.selected.fg=#000000
tab.selected.bg=#47a8ff

statusline_default.fg=#ededed
statusline_default.bg=#0a0a0a
statusline_error.fg=#f13242
statusline_success.fg=#70d9a8

*error.bold=true
*error.fg=#f13242
*warning.fg=#ffae00
*success.fg=#70d9a8

dirlist_*.bg=#000000
dirlist_*.fg=#ededed
dirlist_*.selected.bg=#1f3e70
dirlist_*.selected.fg=#ededed

msglist_*.bg=#000000
msglist_*.fg=#ededed
msglist_*.selected.bg=#1f3e70
#msglist_*.selected.fg=#ededed
msglist_unread.bold=true
msglist_unread.fg=#47a8ff
msglist_marked.fg=#ff9300
msglist_thread_folded.italic=true
msglist_thread_folded.underline=true
msglist_gutter.bg=#1a1a1a
msglist_pill.bg=#2e2e2e
msglist_pill.reverse=false

part_*.fg=#ededed
part_*.bg=#0a0a0a
part_*.selected.fg=#ededed
part_*.selected.bg=#2e2e2e

completion_default.bg=#0a0a0a
completion_default.fg=#ededed
completion_default.selected.bg=#2e2e2e
completion_default.selected.fg=#ededed
completion_gutter.bg=#1a1a1a
completion_pill.bg=#2e2e2e
completion_pill.reverse=false

spinner.bg=#000000
spinner.fg=#ededed

selector_focused.bold=false
selector_focused.bg=#1f3e70
selector_focused.fg=#ededed
selector_chooser.bold=false
selector_chooser.bg=#1f3e70
selector_chooser.fg=#ededed
default.selected.bold=false
default.selected.fg=#ededed
default.selected.bg=#1f3e70

[viewer]
url.underline=true
url.fg=#878787
header.fg=#c472fb
signature.fg=#9440d5
diff_add.fg=#002b0f
diff_del.fg=#3c0d11
diff_meta.bold=true
diff_chunk.dim=true
quote_1.fg=#ffae00
quote_2.fg=#00ac3a
quote_3.fg=#00aa95
quote_3.dim=true
quote_4.fg=#47a8ff
quote_4.dim=true
quote_x.fg=#a0a0a0
quote_x.dim=true

