# vim: ft=dosini
#
# aerc Vercel styleset
# set styleset-name=vercel-xxx.ini in 'aerc.conf' to load the style
#

*.default=true
*.normal=true

border.fg=#c9c9c9
border.bg=#ffffff

title.fg=#cccccc
title.bg=#0084d4
title.bold=true

header.fg=#d22a38
#header.bg=#ffffff
header.bold=true

tab.fg=#c9c9c9
tab.bg=#eeeeee
tab.selected.fg=#cccccc
tab.selected.bg=#0084d4

statusline_default.fg=#515151
statusline_default.bg=#eeeeee
statusline_error.fg=#d22a38
statusline_success.fg=#397458

*error.bold=true
*error.fg=#d22a38
*warning.fg=#946300
*success.fg=#397458

dirlist_*.bg=#ffffff
dirlist_*.fg=#515151
dirlist_*.selected.bg=#9cb4f0
dirlist_*.selected.fg=#515151

msglist_*.bg=#ffffff
msglist_*.fg=#515151
msglist_*.selected.bg=#9cb4f0
#msglist_*.selected.fg=#515151
msglist_unread.bold=true
msglist_unread.fg=#0084d4
msglist_marked.fg=#ab6500
msglist_thread_folded.italic=true
msglist_thread_folded.underline=true
msglist_gutter.bg=#e4e4e4
msglist_pill.bg=#c9c9c9
msglist_pill.reverse=false

part_*.fg=#515151
part_*.bg=#eeeeee
part_*.selected.fg=#515151
part_*.selected.bg=#c9c9c9

completion_default.bg=#eeeeee
completion_default.fg=#515151
completion_default.selected.bg=#c9c9c9
completion_default.selected.fg=#515151
completion_gutter.bg=#e4e4e4
completion_pill.bg=#c9c9c9
completion_pill.reverse=false

spinner.bg=#ffffff
spinner.fg=#515151

selector_focused.bold=false
selector_focused.bg=#9cb4f0
selector_focused.fg=#515151
selector_chooser.bold=false
selector_chooser.bg=#9cb4f0
selector_chooser.fg=#515151
default.selected.bold=false
default.selected.fg=#515151
default.selected.bg=#9cb4f0

[viewer]
url.underline=true
url.fg=#676767
header.fg=#bd55fa
signature.fg=#bd55fa
diff_add.fg=#bfe7cd
diff_del.fg=#f4cacd
diff_meta.bold=true
diff_chunk.dim=true
quote_1.fg=#946300
quote_2.fg=#009f35
quote_3.fg=#009885
quote_3.dim=true
quote_4.fg=#0084d4
quote_4.dim=true
quote_x.fg=#808080
quote_x.dim=true

