[colors]
foreground = "#171717"
background = "#ffffff"
cursor_bg = "#171717"
cursor_border = "#171717"
cursor_fg = "#ffffff"
selection_bg = "#cae7ff"
selection_fg = "#171717"
split = "#005ff2"
compose_cursor = "#aa4d00"
scrollbar_thumb = "#f2f2f2"

ansi = ["#171717", "#fc0035", "#28a948", "#ffae00", "#005ff2", "#a000f8", "#00ac96", "#4d4d4d"]
brights = ["#a8a8a8", "#fc0035", "#28a948", "#ffae00", "#005ff2", "#a000f8", "#00ac96", "#171717"]

[colors.tab_bar]
inactive_tab_edge = "#fafafa"
background = "#ffffff"

[colors.tab_bar.active_tab]
fg_color = "#fafafa"
bg_color = "#005ff2"

[colors.tab_bar.inactive_tab]
fg_color = "#c9c9c9"
bg_color = "#f2f2f2"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#005ff2"
bg_color = "#f2f2f2"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#005ff2"
bg_color = "#ffffff"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#005ff2"
bg_color = "#ffffff"

[metadata]
aliases = []
author = "PunGrumpy"
name = "vercel_light"