[colors]
foreground = "#ededed"
background = "#000000"
cursor_bg = "#ededed"
cursor_border = "#ededed"
cursor_fg = "#000000"
selection_bg = "#003674"
selection_fg = "#ededed"
split = "#47a8ff"
compose_cursor = "#ff9300"
scrollbar_thumb = "#1a1a1a"

ansi = ["#000000", "#f13242", "#00ac3a", "#ffae00", "#47a8ff", "#9440d5", "#00aa95", "#a0a0a0"]
brights = ["#878787", "#f13242", "#00ac3a", "#ffae00", "#47a8ff", "#9440d5", "#00aa95", "#ededed"]

[colors.tab_bar]
inactive_tab_edge = "#000000"
background = "#000000"

[colors.tab_bar.active_tab]
fg_color = "#000000"
bg_color = "#47a8ff"

[colors.tab_bar.inactive_tab]
fg_color = "#454545"
bg_color = "#1a1a1a"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#47a8ff"
bg_color = "#1a1a1a"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#47a8ff"
bg_color = "#000000"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#47a8ff"
bg_color = "#000000"

[metadata]
aliases = []
author = "PunGrumpy"
name = "vercel_dark"