[colors]
foreground = "#515151"
background = "#ffffff"
cursor_bg = "#515151"
cursor_border = "#515151"
cursor_fg = "#ffffff"
selection_bg = "#9cb4f0"
selection_fg = "#515151"
split = "#0084d4"
compose_cursor = "#ab6500"
scrollbar_thumb = "#e4e4e4"

ansi = ["#cccccc", "#d22a38", "#009f35", "#946300", "#0084d4", "#bd55fa", "#009885", "#808080"]
brights = ["#676767", "#f6002b", "#00ae3b", "#a56f00", "#0091e9", "#c56bff", "#00a692", "#515151"]

[colors.tab_bar]
inactive_tab_edge = "#eeeeee"
background = "#ffffff"

[colors.tab_bar.active_tab]
fg_color = "#eeeeee"
bg_color = "#0084d4"

[colors.tab_bar.inactive_tab]
fg_color = "#adadad"
bg_color = "#e4e4e4"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#0084d4"
bg_color = "#e4e4e4"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#0084d4"
bg_color = "#ffffff"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#0084d4"
bg_color = "#ffffff"

[metadata]
aliases = []
author = "PunGrumpy"
name = "vercel_light"