[[themes]]
name = "Vercel Light"
[themes.palette]
background = "#fafafa"
foreground = "#4d4d4d"
black = "#a8a8a8"
red = "#d8001b"
green = "#107d32"
yellow = "#ffae00"
blue = "#005ff2"
magenta = "#a000f8"
cyan = "#00ac96"
white = "#4d4d4d"
bright_black = "#ffffff"
bright_red = "#fc0035"
bright_green = "#007f70"
bright_yellow = "#aa4d00"
bright_blue = "#005ff2"
bright_magenta = "#f22782"
bright_cyan = "#005ff2"
bright_white = "#171717"
