[[themes]]
name = "Vercel Light"
[themes.palette]
background = "#eeeeee"
foreground = "#808080"
black = "#676767"
red = "#d22a38"
green = "#009f35"
yellow = "#946300"
blue = "#0084d4"
magenta = "#bd55fa"
cyan = "#009885"
white = "#808080"
bright_black = "#ffffff"
bright_red = "#d22a38"
bright_green = "#397458"
bright_yellow = "#ab6500"
bright_blue = "#0065fe"
bright_magenta = "#cc236d"
bright_cyan = "#0065fe"
bright_white = "#515151"
