[[themes]]
name = "Vercel"
[themes.palette]
background = "#0a0a0a"
foreground = "#a0a0a0"
black = "#878787"
red = "#f13242"
green = "#00ac3a"
yellow = "#ffae00"
blue = "#47a8ff"
magenta = "#9440d5"
cyan = "#00aa95"
white = "#a0a0a0"
bright_black = "#000000"
bright_red = "#f13242"
bright_green = "#70d9a8"
bright_yellow = "#ff9300"
bright_blue = "#a6b5ff"
bright_magenta = "#f12b82"
bright_cyan = "#a6b5ff"
bright_white = "#ededed"
