attribute = { fg = "#c472fb" }
comment = { fg = "#a0a0a0", modifiers = ["italic"] }
"comment.block.documentation" = { fg = "#00ca50" }
constant = { fg = "#47a8ff" }
"constant.builtin" = { fg = "#47a8ff" }
"constant.builtin.boolean" = { fg = "#47a8ff" }
"constant.character" = { fg = "#ededed" }
"constant.character.escape" = { fg = "#00ca50" }
"constant.numeric" = { fg = "#47a8ff" }
"constant.numeric.float" = { fg = "#47a8ff" }
"constant.numeric.integer" = { fg = "#47a8ff" }
constructor = { fg = "#c472fb" }
"diagnostic.error" = { underline = { style = "curl" } }
"diagnostic.hint" = { underline = { style = "curl" } }
"diagnostic.info" = { underline = { style = "curl" } }
"diagnostic.warning" = { underline = { style = "curl" } }
"diff.delta" = { bg = "#00050b", fg = "#47a8ff" }
"diff.delta.moved" = { fg = "#47a8ff" }
"diff.minus" = { bg = "#3c0d11", fg = "#ff565f" }
"diff.plus" = { bg = "#002b0f", fg = "#00ca50" }
error = { fg = "#f13242" }
function = { fg = "#c472fb" }
"function.builtin" = { fg = "#c472fb" }
"function.macro" = { fg = "#ff4d8d" }
"function.method" = { fg = "#c472fb" }
"function.special" = { fg = "#ff4d8d" }
hint = { fg = "#00aa95" }
info = { fg = "#006efe" }
keyword = { fg = "#ff4d8d" }
"keyword.control" = { fg = "#ff4d8d" }
"keyword.control.conditional" = { fg = "#ff4d8d" }
"keyword.control.exception" = { fg = "#ff4d8d" }
"keyword.control.repeat" = { fg = "#ff4d8d" }
"keyword.control.return" = { fg = "#ff4d8d" }
"keyword.directive" = { fg = "#ff4d8d" }
"keyword.function" = { fg = "#ff4d8d" }
"keyword.operator" = { fg = "#ff4d8d" }
label = { fg = "#ff4d8d" }
"markup.bold" = { fg = "#ededed", modifiers = ["bold"] }
"markup.heading" = { fg = "#47a8ff", modifiers = ["bold"] }
"markup.heading.completion" = { bg = "#000000", fg = "#ededed" }
"markup.heading.hover" = { bg = "#252525" }
"markup.italic" = { fg = "#ededed", modifiers = ["italic"] }
"markup.link" = { fg = "#00ca50", underline = { style = "line" } }
"markup.link.label" = { fg = "#ededed" }
"markup.link.text" = { fg = "#00ca50", underline = { style = "line" } }
"markup.link.url" = { underline = { style = "line" } }
"markup.list" = { fg = "#47a8ff" }
"markup.normal.completion" = { fg = "#a0a0a0" }
"markup.normal.hover" = { fg = "#a0a0a0" }
"markup.raw" = { fg = "#00ca50" }
"markup.raw.inline" = { fg = "#00ca50" }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
namespace = { fg = "#ededed" }
operator = { fg = "#ff4d8d" }
special = { fg = "#ededed" }
string = { fg = "#00ca50" }
"string.regexp" = { fg = "#00ca50" }
"string.special" = { fg = "#ededed" }
tag = { fg = "#47a8ff" }
type = { fg = "#c472fb" }
"type.builtin" = { fg = "#47a8ff" }
"type.enum" = { fg = "#c472fb" }
"type.enum.variant" = { fg = "#47a8ff" }
"ui.background" = { bg = "bg" }
"ui.bufferline.active" = { bg = "bg_visual", fg = "fg" }
"ui.cursor" = { bg = "#ededed", fg = "#000000" }
"ui.cursor.match" = { fg = "#ff9300", modifiers = ["bold"] }
"ui.linenr" = { fg = "#878787" }
"ui.linenr.select" = { fg = "#ededed", modifiers = ["bold"] }
"ui.menu" = { bg = "#000000", fg = "#ededed" }
"ui.menu.scroll" = { bg = 789516, fg = 3026478 }
"ui.menu.selected" = { bg = "#252525" }
"ui.popup" = { bg = "#000000", fg = "#3986cc" }
"ui.selection" = { bg = "bg_highlight" }
"ui.statusline" = { bg = "#000000", fg = "#a0a0a0" }
"ui.statusline.inactive" = { bg = "#000000", fg = "#2e2e2e" }
"ui.statusline.normal" = { bg = "blue", fg = "black" }
"ui.text" = { bg = "#000000", fg = "#ededed" }
"ui.text.focus" = { bg = "#003674" }
"ui.text.inactive" = { fg = "#a0a0a0", modifiers = ["italic"] }
"ui.text.info" = { bg = "#000000", fg = "#ededed" }
"ui.virtual.inlay-hint" = { bg = "#00110f", fg = "#00aa95" }
"ui.window" = { fg = "#2e2e2e", modifiers = ["bold"] }
variable = { fg = "#ededed" }
"variable.builtin" = { fg = "#47a8ff" }
"variable.other.member" = { fg = "#ededed" }
"variable.parameter" = { fg = "#ff9300" }
warning = { fg = "#ffae00" }

[palette]
bg = "#000000"
bg_dark = "#000000"
bg_dark1 = "#000000"
bg_float = "#000000"
bg_highlight = "#1a1a1a"
bg_popup = "#000000"
bg_search = "#003674"
bg_sidebar = "#000000"
bg_statusline = "#000000"
bg_visual = "#003674"
black = "#000000"
blue = "#47a8ff"
blue0 = "#003674"
blue1 = "#47a8ff"
blue2 = "#006efe"
blue5 = "#47a8ff"
blue6 = "#47a8ff"
blue7 = "#022248"
border = "#2e2e2e"
border_highlight = "#3986cc"
comment = "#a0a0a0"
cyan = "#00aa95"
dark3 = "#454545"
dark5 = "#878787"
"diff.add" = "#002b0f"
"diff.change" = "#00050b"
"diff.delete" = "#3c0d11"
"diff.text" = "#022248"
error = "#f13242"
fg = "#ededed"
fg_dark = "#a0a0a0"
fg_float = "#ededed"
fg_gutter = "#2e2e2e"
fg_sidebar = "#a0a0a0"
"git.add" = "#00ca50"
"git.change" = "#47a8ff"
"git.delete" = "#ff565f"
"git.ignore" = "#454545"
green = "#00ca50"
green1 = "#00cfb7"
green2 = "#00ac3a"
hint = "#00aa95"
info = "#006efe"
magenta = "#9440d5"
magenta2 = "#f12b82"
orange = "#ff9300"
pink = "#ff4d8d"
purple = "#c472fb"
rainbow = "#47a8ff"
"rainbow.2" = "#ffae00"
"rainbow.3" = "#00ca50"
"rainbow.4" = "#00aa95"
"rainbow.5" = "#9440d5"
"rainbow.6" = "#c472fb"
"rainbow.7" = "#ff9300"
"rainbow.8" = "#ff565f"
red = "#ff565f"
red1 = "#f13242"
teal = "#00aa95"
"terminal.black" = "#000000"
"terminal.black_bright" = "#878787"
"terminal.blue" = "#47a8ff"
"terminal.blue_bright" = "#47a8ff"
"terminal.cyan" = "#00aa95"
"terminal.cyan_bright" = "#00aa95"
"terminal.green" = "#00ac3a"
"terminal.green_bright" = "#00ac3a"
"terminal.magenta" = "#9440d5"
"terminal.magenta_bright" = "#9440d5"
"terminal.red" = "#f13242"
"terminal.red_bright" = "#f13242"
"terminal.white" = "#a0a0a0"
"terminal.white_bright" = "#ededed"
"terminal.yellow" = "#ffae00"
"terminal.yellow_bright" = "#ffae00"
terminal_black = "#878787"
todo = "#47a8ff"
warning = "#ffae00"
yellow = "#ffae00"