attribute = { fg = "#7d00cc" }
comment = { fg = "#4d4d4d", modifiers = ["italic"] }
"comment.block.documentation" = { fg = "#107d32" }
constant = { fg = "#005ff2" }
"constant.builtin" = { fg = "#005ff2" }
"constant.builtin.boolean" = { fg = "#005ff2" }
"constant.character" = { fg = "#171717" }
"constant.character.escape" = { fg = "#107d32" }
"constant.numeric" = { fg = "#005ff2" }
"constant.numeric.float" = { fg = "#005ff2" }
"constant.numeric.integer" = { fg = "#005ff2" }
constructor = { fg = "#7d00cc" }
"diagnostic.error" = { underline = { style = "curl" } }
"diagnostic.hint" = { underline = { style = "curl" } }
"diagnostic.info" = { underline = { style = "curl" } }
"diagnostic.warning" = { underline = { style = "curl" } }
"diff.delta" = { bg = "#fcfdff", fg = "#005ff2" }
"diff.delta.moved" = { fg = "#005ff2" }
"diff.minus" = { bg = "#febfcd", fg = "#d8001b" }
"diff.plus" = { bg = "#c9ead1", fg = "#107d32" }
error = { fg = "#fc0035" }
function = { fg = "#7d00cc" }
"function.builtin" = { fg = "#7d00cc" }
"function.macro" = { fg = "#c41562" }
"function.method" = { fg = "#7d00cc" }
"function.special" = { fg = "#c41562" }
hint = { fg = "#00ac96" }
info = { fg = "#006bff" }
keyword = { fg = "#c41562" }
"keyword.control" = { fg = "#c41562" }
"keyword.control.conditional" = { fg = "#c41562" }
"keyword.control.exception" = { fg = "#c41562" }
"keyword.control.repeat" = { fg = "#c41562" }
"keyword.control.return" = { fg = "#c41562" }
"keyword.directive" = { fg = "#c41562" }
"keyword.function" = { fg = "#c41562" }
"keyword.operator" = { fg = "#c41562" }
label = { fg = "#c41562" }
"markup.bold" = { fg = "#171717", modifiers = ["bold"] }
"markup.heading" = { fg = "#005ff2", modifiers = ["bold"] }
"markup.heading.completion" = { bg = "#fafafa", fg = "#171717" }
"markup.heading.hover" = { bg = "#eeeeee" }
"markup.italic" = { fg = "#171717", modifiers = ["italic"] }
"markup.link" = { fg = "#107d32", underline = { style = "line" } }
"markup.link.label" = { fg = "#171717" }
"markup.link.text" = { fg = "#107d32", underline = { style = "line" } }
"markup.link.url" = { underline = { style = "line" } }
"markup.list" = { fg = "#005ff2" }
"markup.normal.completion" = { fg = "#4d4d4d" }
"markup.normal.hover" = { fg = "#4d4d4d" }
"markup.raw" = { fg = "#107d32" }
"markup.raw.inline" = { fg = "#107d32" }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
namespace = { fg = "#171717" }
operator = { fg = "#c41562" }
special = { fg = "#171717" }
string = { fg = "#107d32" }
"string.regexp" = { fg = "#107d32" }
"string.special" = { fg = "#171717" }
tag = { fg = "#005ff2" }
type = { fg = "#7d00cc" }
"type.builtin" = { fg = "#005ff2" }
"type.enum" = { fg = "#7d00cc" }
"type.enum.variant" = { fg = "#005ff2" }
"ui.background" = { bg = "bg" }
"ui.bufferline.active" = { bg = "bg_visual", fg = "fg" }
"ui.cursor" = { bg = "#171717", fg = "#ffffff" }
"ui.cursor.match" = { fg = "#aa4d00", modifiers = ["bold"] }
"ui.linenr" = { fg = "#a8a8a8" }
"ui.linenr.select" = { fg = "#171717", modifiers = ["bold"] }
"ui.menu" = { bg = "#fafafa", fg = "#171717" }
"ui.menu.scroll" = { bg = 15724527, fg = 15395562 }
"ui.menu.selected" = { bg = "#eeeeee" }
"ui.popup" = { bg = "#fafafa", fg = "#337ff5" }
"ui.selection" = { bg = "bg_highlight" }
"ui.statusline" = { bg = "#fafafa", fg = "#4d4d4d" }
"ui.statusline.inactive" = { bg = "#fafafa", fg = "#eaeaea" }
"ui.statusline.normal" = { bg = "blue", fg = "black" }
"ui.text" = { bg = "#ffffff", fg = "#171717" }
"ui.text.focus" = { bg = "#cae7ff" }
"ui.text.inactive" = { fg = "#4d4d4d", modifiers = ["italic"] }
"ui.text.info" = { bg = "#fafafa", fg = "#171717" }
"ui.virtual.inlay-hint" = { bg = "#e6f7f5", fg = "#00ac96" }
"ui.window" = { fg = "#eaeaea", modifiers = ["bold"] }
variable = { fg = "#171717" }
"variable.builtin" = { fg = "#005ff2" }
"variable.other.member" = { fg = "#171717" }
"variable.parameter" = { fg = "#aa4d00" }
warning = { fg = "#ffae00" }

[palette]
bg = "#ffffff"
bg_dark = "#fafafa"
bg_dark1 = "#f2f2f2"
bg_float = "#fafafa"
bg_highlight = "#f2f2f2"
bg_popup = "#fafafa"
bg_search = "#cae7ff"
bg_sidebar = "#fafafa"
bg_statusline = "#fafafa"
bg_visual = "#cae7ff"
black = "#ffffff"
blue = "#005ff2"
blue0 = "#cae7ff"
blue1 = "#005ff2"
blue2 = "#006bff"
blue5 = "#005ff2"
blue6 = "#005ff2"
blue7 = "#e9f4ff"
border = "#eaeaea"
border_highlight = "#337ff5"
comment = "#4d4d4d"
cyan = "#00ac96"
dark3 = "#c9c9c9"
dark5 = "#a8a8a8"
"diff.add" = "#c9ead1"
"diff.change" = "#fcfdff"
"diff.delete" = "#febfcd"
"diff.text" = "#e9f4ff"
error = "#fc0035"
fg = "#171717"
fg_dark = "#4d4d4d"
fg_float = "#171717"
fg_gutter = "#eaeaea"
fg_sidebar = "#4d4d4d"
"git.add" = "#107d32"
"git.change" = "#005ff2"
"git.delete" = "#d8001b"
"git.ignore" = "#c9c9c9"
green = "#107d32"
green1 = "#007f70"
green2 = "#28a948"
hint = "#00ac96"
info = "#006bff"
magenta = "#a000f8"
magenta2 = "#f22782"
orange = "#aa4d00"
pink = "#c41562"
purple = "#7d00cc"
rainbow = "#005ff2"
"rainbow.2" = "#ffae00"
"rainbow.3" = "#107d32"
"rainbow.4" = "#00ac96"
"rainbow.5" = "#a000f8"
"rainbow.6" = "#7d00cc"
"rainbow.7" = "#aa4d00"
"rainbow.8" = "#d8001b"
red = "#d8001b"
red1 = "#fc0035"
teal = "#00ac96"
"terminal.black" = "#171717"
"terminal.black_bright" = "#a8a8a8"
"terminal.blue" = "#005ff2"
"terminal.blue_bright" = "#005ff2"
"terminal.cyan" = "#00ac96"
"terminal.cyan_bright" = "#00ac96"
"terminal.green" = "#28a948"
"terminal.green_bright" = "#28a948"
"terminal.magenta" = "#a000f8"
"terminal.magenta_bright" = "#a000f8"
"terminal.red" = "#fc0035"
"terminal.red_bright" = "#fc0035"
"terminal.white" = "#4d4d4d"
"terminal.white_bright" = "#171717"
"terminal.yellow" = "#ffae00"
"terminal.yellow_bright" = "#ffae00"
terminal_black = "#a8a8a8"
todo = "#005ff2"
warning = "#ffae00"
yellow = "#ffae00"