[mgr]
# NOTE: can be combined with tmTheme (sublime colorshceme file) for preview code highlight
# syntect_theme = "path/to/tmTheme"

cwd = { fg = "#4d4d4d", italic = true }

# Hovered
hovered         = { bg = "#f2f2f2" }
preview_hovered = { bg = "#f2f2f2" }

# Find
find_keyword  = { fg = "#fafafa", bg = "#aa4d00", bold = true }
find_position = { fg = "#006bff", bg = "#e6f0ff", bold = true }

# Marker
marker_copied   = { fg = "#107d32", bg = "#107d32" }
marker_cut      = { fg = "#d8001b", bg = "#d8001b" }
marker_marked   = { fg = "#a000f8", bg = "#a000f8" }
marker_selected = { fg = "#005ff2", bg = "#005ff2" }

# Count
count_copied   = { fg = "#fafafa", bg = "#107d32" }
count_cut      = { fg = "#fafafa", bg = "#d8001b" }
count_selected = { fg = "#fafafa", bg = "#005ff2" }

# Border
border_symbol = "│"
border_style  = { fg = "#337ff5" }

# Tab
[tabs]
active   = { fg = "#ffffff", bg = "#005ff2" }
inactive = { fg = "#005ff2", bg = "#eaeaea" }

[mode]
normal_main = { fg = "#ffffff", bg = "#005ff2", bold = true }
normal_alt  = { fg = "#005ff2", bg = "#eaeaea" }

select_main = { fg = "#ffffff", bg = "#a000f8", bold = true }
select_alt  = { fg = "#a000f8", bg = "#eaeaea" }

unset_main  = { fg = "#ffffff", bg = "#7d00cc", bold = true }
unset_alt   = { fg = "#7d00cc", bg = "#eaeaea" }

[status]
overall   = { fg = "#171717", bg = "#fafafa" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Progress
progress_label  = { fg = "#171717", bold = true }
progress_normal = { fg = "#cae7ff", bg = "#f2f2f2" }
progress_error  = { fg = "#fc0035", bg = "#f2f2f2" }

# Permissions
perm_type  = { fg = "#005ff2" }
perm_read  = { fg = "#ffae00" }
perm_write = { fg = "#d8001b" }
perm_exec  = { fg = "#107d32" }
perm_sep   = { fg = "#a8a8a8" }

[pick]
border   = { fg = "#337ff5" }
active   = { fg = "#171717",  bg = "#cae7ff" }
inactive = { fg = "#171717" }

# Input
[input]
border   = { fg = "#006bff" }
title    = { fg = "#006bff" }
value    = { fg = "#7d00cc" }
selected = { bg = "#cae7ff" }

# Completion
[cmp]
border   = { fg = "#006bff" }
active   = { fg = "#171717", bg = "#eeeeee" }
inactive = { fg = "#171717" }

icon_file    = ""
icon_folder  = ""
icon_command = ""

# Tasks
[tasks]
border  = { fg = "#337ff5" }
title   = { fg = "#337ff5" }
hovered = { fg = "#171717", bg = "#cae7ff" }

# Which
[which]
cols            = 3
mask            = { bg = "#fafafa" }
cand            = { fg = "#00ac96" }
rest            = { fg = "#005ff2" }
desc            = { fg = "#a000f8" }
separator       = " ➜ "
separator_style = { fg = "#4d4d4d" }

# Confirm
[confirm]
border  = { fg = "#006bff" }
title   = { fg = "#337ff5" }
content = {}
list    = {}
btn_yes = { bg = "#cae7ff" }
btn_no  = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# Spot
[spot]
border  = { fg = "#337ff5" }
title   = { fg = "#337ff5" }

# Notify
[notify]
title_info  = { fg = "#006bff" }
title_warn  = { fg = "#ffae00" }
title_error = { fg = "#fc0035" }

icon_error = ""
icon_warn = ""
icon_info = ""

# Help
[help]
on      = { fg = "#107d32" }
run     = { fg = "#a000f8" }
desc    = { fg = "#00ac96" }
hovered = { bg = "#f2f2f2" }
footer  = { fg = "#171717", bg = "#ffffff" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#ffae00" },

	# Media
	{ mime = "{audio,video}/*", fg = "#a000f8" },

	# Archives
	{ mime = "application/*zip", fg = "#d8001b" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#d8001b" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#00ac96" },

	# Empty files
	# { mime = "inode/x-empty", fg = "#d8001b" },

	# Special files
	{ name = "*", is = "orphan", bg = "#d8001b" },
	{ name = "*", is = "exec"  , fg = "#107d32" },

	# Fallback
	{ name = "*/", fg = "#005ff2" },
	{ name = "*", fg = "#171717" }
]
    