[mgr]
# NOTE: can be combined with tmTheme (sublime colorshceme file) for preview code highlight
# syntect_theme = "path/to/tmTheme"

cwd = { fg = "#808080", italic = true }

# Hovered
hovered         = { bg = "#e4e4e4" }
preview_hovered = { bg = "#e4e4e4" }

# Find
find_keyword  = { fg = "#eeeeee", bg = "#ab6500", bold = true }
find_position = { fg = "#0084d4", bg = "#e6f3fb", bold = true }

# Marker
marker_copied   = { fg = "#009f35", bg = "#009f35" }
marker_cut      = { fg = "#d22a38", bg = "#d22a38" }
marker_marked   = { fg = "#bd55fa", bg = "#bd55fa" }
marker_selected = { fg = "#0084d4", bg = "#0084d4" }

# Count
count_copied   = { fg = "#eeeeee", bg = "#009f35" }
count_cut      = { fg = "#eeeeee", bg = "#d22a38" }
count_selected = { fg = "#eeeeee", bg = "#0084d4" }

# Border
border_symbol = "│"
border_style  = { fg = "#3384fe" }

# Tab
[tabs]
active   = { fg = "#cccccc", bg = "#0084d4" }
inactive = { fg = "#0084d4", bg = "#c9c9c9" }

[mode]
normal_main = { fg = "#cccccc", bg = "#0084d4", bold = true }
normal_alt  = { fg = "#0084d4", bg = "#c9c9c9" }

select_main = { fg = "#cccccc", bg = "#bd55fa", bold = true }
select_alt  = { fg = "#bd55fa", bg = "#c9c9c9" }

unset_main  = { fg = "#cccccc", bg = "#bd55fa", bold = true }
unset_alt   = { fg = "#bd55fa", bg = "#c9c9c9" }

[status]
overall   = { fg = "#515151", bg = "#eeeeee" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Progress
progress_label  = { fg = "#515151", bold = true }
progress_normal = { fg = "#9cb4f0", bg = "#e4e4e4" }
progress_error  = { fg = "#d22a38", bg = "#e4e4e4" }

# Permissions
perm_type  = { fg = "#0084d4" }
perm_read  = { fg = "#946300" }
perm_write = { fg = "#d22a38" }
perm_exec  = { fg = "#009f35" }
perm_sep   = { fg = "#676767" }

[pick]
border   = { fg = "#3384fe" }
active   = { fg = "#515151",  bg = "#9cb4f0" }
inactive = { fg = "#515151" }

# Input
[input]
border   = { fg = "#0084d4" }
title    = { fg = "#0084d4" }
value    = { fg = "#bd55fa" }
selected = { bg = "#9cb4f0" }

# Completion
[cmp]
border   = { fg = "#0084d4" }
active   = { fg = "#515151", bg = "#d4d4d4" }
inactive = { fg = "#515151" }

icon_file    = ""
icon_folder  = ""
icon_command = ""

# Tasks
[tasks]
border  = { fg = "#3384fe" }
title   = { fg = "#3384fe" }
hovered = { fg = "#515151", bg = "#9cb4f0" }

# Which
[which]
cols            = 3
mask            = { bg = "#eeeeee" }
cand            = { fg = "#009885" }
rest            = { fg = "#0084d4" }
desc            = { fg = "#bd55fa" }
separator       = " ➜ "
separator_style = { fg = "#808080" }

# Confirm
[confirm]
border  = { fg = "#0084d4" }
title   = { fg = "#3384fe" }
content = {}
list    = {}
btn_yes = { bg = "#9cb4f0" }
btn_no  = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# Spot
[spot]
border  = { fg = "#3384fe" }
title   = { fg = "#3384fe" }

# Notify
[notify]
title_info  = { fg = "#0084d4" }
title_warn  = { fg = "#946300" }
title_error = { fg = "#d22a38" }

icon_error = ""
icon_warn = ""
icon_info = ""

# Help
[help]
on      = { fg = "#009f35" }
run     = { fg = "#bd55fa" }
desc    = { fg = "#009885" }
hovered = { bg = "#e4e4e4" }
footer  = { fg = "#515151", bg = "#ffffff" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#946300" },

	# Media
	{ mime = "{audio,video}/*", fg = "#bd55fa" },

	# Archives
	{ mime = "application/*zip", fg = "#d22a38" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#d22a38" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#009885" },

	# Empty files
	# { mime = "inode/x-empty", fg = "#d22a38" },

	# Special files
	{ name = "*", is = "orphan", bg = "#d22a38" },
	{ name = "*", is = "exec"  , fg = "#009f35" },

	# Fallback
	{ name = "*/", fg = "#0084d4" },
	{ name = "*", fg = "#515151" }
]
    