# vim:ft=kitty

## name: Vercel Light
## license: MIT
## author: Folke Lemaitre
## upstream: https://github.com/PunGrumpy/vercel.nvim/raw/main/extras/kitty/vercel_light.conf


background #ffffff
foreground #515151
selection_background #9cb4f0
selection_foreground #515151
url_color #397458
cursor #515151
cursor_text_color #ffffff

# Tabs
active_tab_background #0084d4
active_tab_foreground #eeeeee
inactive_tab_background #e4e4e4
inactive_tab_foreground #adadad
#tab_bar_background #cccccc

# Windows
active_border_color #0084d4
inactive_border_color #e4e4e4

# normal
color0 #cccccc
color1 #d22a38
color2 #009f35
color3 #946300
color4 #0084d4
color5 #bd55fa
color6 #009885
color7 #808080

# bright
color8  #676767
color9  #f6002b
color10 #00ae3b
color11 #a56f00
color12 #0091e9
color13 #c56bff
color14 #00a692
color15 #515151

# extended colors
color16 #ab6500
color17 #d22a38
