# vim:ft=kitty

## name: Vercel Light
## license: MIT
## author: Folke Lemaitre
## upstream: https://github.com/PunGrumpy/vercel.nvim/raw/main/extras/kitty/vercel_light.conf


background #ffffff
foreground #171717
selection_background #cae7ff
selection_foreground #171717
url_color #007f70
cursor #171717
cursor_text_color #ffffff

# Tabs
active_tab_background #005ff2
active_tab_foreground #fafafa
inactive_tab_background #f2f2f2
inactive_tab_foreground #c9c9c9
#tab_bar_background #ffffff

# Windows
active_border_color #005ff2
inactive_border_color #f2f2f2

# normal
color0 #171717
color1 #fc0035
color2 #28a948
color3 #ffae00
color4 #005ff2
color5 #a000f8
color6 #00ac96
color7 #4d4d4d

# bright
color8  #a8a8a8
color9  #fc0035
color10 #28a948
color11 #ffae00
color12 #005ff2
color13 #a000f8
color14 #00ac96
color15 #171717

# extended colors
color16 #aa4d00
color17 #fc0035
