# vim:ft=kitty

## name: Vercel
## license: MIT
## author: Folke Lemaitre
## upstream: https://github.com/PunGrumpy/vercel.nvim/raw/main/extras/kitty/vercel_dark.conf


background #000000
foreground #ededed
selection_background #003674
selection_foreground #ededed
url_color #00cfb7
cursor #ededed
cursor_text_color #000000

# Tabs
active_tab_background #47a8ff
active_tab_foreground #000000
inactive_tab_background #1a1a1a
inactive_tab_foreground #454545
#tab_bar_background #000000

# Windows
active_border_color #47a8ff
inactive_border_color #1a1a1a

# normal
color0 #000000
color1 #f13242
color2 #00ac3a
color3 #ffae00
color4 #47a8ff
color5 #9440d5
color6 #00aa95
color7 #a0a0a0

# bright
color8  #878787
color9  #f13242
color10 #00ac3a
color11 #ffae00
color12 #47a8ff
color13 #9440d5
color14 #00aa95
color15 #ededed

# extended colors
color16 #ff9300
color17 #f13242
