# -----------------------------------------------------------------------------
# Theme: Vercel Light
# Upstream: https://github.com/PunGrumpy/vercel.nvim/raw/main/extras/termux/vercel_light.properties
# -----------------------------------------------------------------------------

background: #ffffff
foreground: #515151

# Normal colors
color0:  #cccccc
color1:  #d22a38
color2:  #009f35
color3:  #946300
color4:  #0084d4
color5:  #bd55fa
color6:  #009885
color7:  #808080

# Bright colors
color8:  #676767
color9:  #f6002b
color10: #00ae3b
color11: #a56f00
color12: #0091e9
color13: #c56bff
color14: #00a692
color15: #515151

# Extended colors
color16: #ab6500
color17: #d22a38
