# -----------------------------------------------------------------------------
# Theme: Vercel Light
# Upstream: https://github.com/PunGrumpy/vercel.nvim/raw/main/extras/termux/vercel_light.properties
# -----------------------------------------------------------------------------

background: #ffffff
foreground: #171717

# Normal colors
color0:  #171717
color1:  #fc0035
color2:  #28a948
color3:  #ffae00
color4:  #005ff2
color5:  #a000f8
color6:  #00ac96
color7:  #4d4d4d

# Bright colors
color8:  #a8a8a8
color9:  #fc0035
color10: #28a948
color11: #ffae00
color12: #005ff2
color13: #a000f8
color14: #00ac96
color15: #171717

# Extended colors
color16: #aa4d00
color17: #fc0035
