# -----------------------------------------------------------------------------
# Theme: Vercel
# Upstream: https://github.com/PunGrumpy/vercel.nvim/raw/main/extras/termux/vercel_dark.properties
# -----------------------------------------------------------------------------

background: #000000
foreground: #ededed

# Normal colors
color0:  #000000
color1:  #f13242
color2:  #00ac3a
color3:  #ffae00
color4:  #47a8ff
color5:  #c472fb
color6:  #00aa95
color7:  #a1a1a1

# Bright colors
color8:  #878787
color9:  #ff4753
color10: #00bb40
color11: #ffc076
color12: #71b4ff
color13: #cc86ff
color14: #00b9a2
color15: #ededed

# Extended colors
color16: #ff990a
color17: #f13242
